version: "3.9"
services:
  cfalerter:
    build: .
    links:
      - mailserver
    depends_on:
      - mailserver
  mailserver:
    image: "python:3"
    command: python -m smtpd -c DebuggingServer -n 0.0.0.0:1025
    ports:
      - "1025:1025"